spes: Do not use permissive domain for recovery
This breaks user builds with:
ERROR: permissive domains not allowed in user builds
List of invalid domains:
recovery

Change-Id: I4c3aaf91f3ac8fdbafc72be6891687026f8da4c3